In [1]:
import numpy as np
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler

In [2]:
#load in data
heart_stroke_df = pd.read_csv('healthcare-dataset-stroke-data.csv')
heart_stroke_df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

## Data Cleaning

In [3]:
heart_stroke_df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [4]:
# replace yes with 1 and no with 0
heart_stroke_df["ever_married"] = heart_stroke_df["ever_married"].replace("Yes", 1)
heart_stroke_df["ever_married"] = heart_stroke_df["ever_married"].replace("No", 0)

In [5]:
#one hot encode data
genderDF = pd.get_dummies(heart_stroke_df["gender"])
workTypeDF = pd.get_dummies(heart_stroke_df["work_type"])
residenceTypeDF = pd.get_dummies(heart_stroke_df["Residence_type"])
smokingStatuesDF = pd.get_dummies(heart_stroke_df["smoking_status"])

In [6]:
#drop columns that are going to be one hot encoded
heart_stroke_df = heart_stroke_df.drop(["id", "gender", "work_type", "Residence_type", "smoking_status"], axis=1)

In [7]:
#merge the one hot encoded data together with main dataset
adjusted_df = genderDF.join([workTypeDF, residenceTypeDF, smokingStatuesDF])
heart_stroke_df = adjusted_df.join(heart_stroke_df)
heart_stroke_df

,Female,Male,Other,Govt_job,Never_worked,Private,Self-employed,children,Rural,Urban,...,formerly smoked,never smoked,smokes,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke
0,0,1,0,0,0,1,0,0,0,1,...,1,0,0,67.0,0,1,1,228.69,36.6,1
1,1,0,0,0,0,0,1,0,1,0,...,0,1,0,61.0,0,0,1,202.21,NaN,1
2,0,1,0,0,0,1,0,0,1,0,...,0,1,0,80.0,0,1,1,105.92,32.5,1
3,1,0,0,0,0,1,0,0,0,1,...,0,0,1,49.0,0,0,1,171.23,34.4,1
4,1,0,0,0,0,0,1,0,1,0,...,0,1,0,79.0,1,0,1,174.12,24.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,1,0,0,0,0,1,0,0,0,1,...,0,1,0,80.0,1,0,1,83.75,NaN,0
5106,1,0,0,0,0,0,1,0,0,1,...,0,1,0,81.0,0,0,1,125.20,40.0,0
5107,1,0,0,0,0,0,1,0,1,0,...,0,1,0,35.0,0,0,1,82.99,30.6,0
5108,0,1,0,0,0,1,0,0,1,0,...,1,0,0,51.0,0,0,1,166.29,25.6,0
5109,1,0,0,1,0,0,0,0,0,1,...,0,0,0,44.0,0,0,1,85.28,26.2,0

In [8]:
#check for null values
heart_stroke_df.isna().sum().sum()

201

In [9]:
#drop null rows
heart_stroke_df = heart_stroke_df.dropna()
heart_stroke_df

,Female,Male,Other,Govt_job,Never_worked,Private,Self-employed,children,Rural,Urban,...,formerly smoked,never smoked,smokes,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke
0,0,1,0,0,0,1,0,0,0,1,...,1,0,0,67.0,0,1,1,228.69,36.6,1
2,0,1,0,0,0,1,0,0,1,0,...,0,1,0,80.0,0,1,1,105.92,32.5,1
3,1,0,0,0,0,1,0,0,0,1,...,0,0,1,49.0,0,0,1,171.23,34.4,1
4,1,0,0,0,0,0,1,0,1,0,...,0,1,0,79.0,1,0,1,174.12,24.0,1
5,0,1,0,0,0,1,0,0,0,1,...,1,0,0,81.0,0,0,1,186.21,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,1,0,0,0,0,0,0,1,1,0,...,0,0,0,13.0,0,0,0,103.08,18.6,0
5106,1,0,0,0,0,0,1,0,0,1,...,0,1,0,81.0,0,0,1,125.20,40.0,0
5107,1,0,0,0,0,0,1,0,1,0,...,0,1,0,35.0,0,0,1,82.99,30.6,0
5108,0,1,0,0,0,1,0,0,1,0,...,1,0,0,51.0,0,0,1,166.29,25.6,0
5109,1,0,0,1,0,0,0,0,0,1,...,0,0,0,44.0,0,0,1,85.28,26.2,0

In [10]:
#positive rate
heart_stroke_df['stroke'].value_counts()

0    4700
1     209
Name: stroke, dtype: int64

In [11]:
#drop stroke column
heart_stroke_df.drop('stroke', axis=1).head()
# heart_stroke_df.head()

,Female,Male,Other,Govt_job,Never_worked,Private,Self-employed,children,Rural,Urban,Unknown,formerly smoked,never smoked,smokes,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi
0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,67.0,0,1,1,228.69,36.6
2,0,1,0,0,0,1,0,0,1,0,0,0,1,0,80.0,0,1,1,105.92,32.5
3,1,0,0,0,0,1,0,0,0,1,0,0,0,1,49.0,0,0,1,171.23,34.4
4,1,0,0,0,0,0,1,0,1,0,0,0,1,0,79.0,1,0,1,174.12,24.0
5,0,1,0,0,0,1,0,0,0,1,0,1,0,0,81.0,0,0,1,186.21,29.0

In [12]:
# #reset index
# heart_stroke_df = heart_stroke_df.reset_index()
# heart_stroke_df

PCA

In [13]:
#scaling data
heart_stroke_df_scaled = StandardScaler().fit_transform(heart_stroke_df)
pd.DataFrame(heart_stroke_df_scaled).head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,-1.199942,1.200447,-0.014274,-0.383706,-0.067095,0.863918,-0.432978,-0.397906,-0.985640,0.985640,...,2.205673,-0.778346,-0.420302,1.070138,-0.318067,4.381968,0.729484,2.777698,0.981345,4.742155
1,-1.199942,1.200447,-0.014274,-0.383706,-0.067095,0.863918,-0.432978,-0.397906,1.014569,-1.014569,...,-0.453376,1.284775,-0.420302,1.646563,-0.318067,4.381968,0.729484,0.013842,0.459269,4.742155
2,0.833374,-0.833023,-0.014274,-0.383706,-0.067095,0.863918,-0.432978,-0.397906,-0.985640,0.985640,...,-0.453376,-0.778346,2.379241,0.272012,-0.318067,-0.228208,0.729484,1.484132,0.701207,4.742155
3,0.833374,-0.833023,-0.014274,-0.383706,-0.067095,-1.157518,2.309587,-0.397906,1.014569,-1.014569,...,-0.453376,1.284775,-0.420302,1.602222,3.143994,-0.228208,0.729484,1.549193,-0.623083,4.742155
4,-1.199942,1.200447,-0.014274,-0.383706,-0.067095,0.863918,-0.432978,-0.397906,-0.985640,0.985640,...,2.205673,-0.778346,-0.420302,1.690903,-0.318067,-0.228208,0.729484,1.821368,0.013595,4.742155

In [14]:
#covariance matrix
attributes = heart_stroke_df_scaled.T
covariance_matrix = np.cov(attributes)
covariance_matrix

array([[ 1.00020375e+00, -9.99782619e-01, -1.71315422e-02,
         1.51258237e-02, -1.22999597e-02,  3.86190242e-02,
         2.23163042e-02, -9.16379759e-02, -4.59906393e-03,
         4.59906393e-03, -5.79052883e-02, -3.96001774e-02,
         9.40704744e-02, -1.15210927e-02,  3.04628787e-02,
        -2.17342582e-02, -8.28989600e-02,  3.67105396e-02,
        -5.33692356e-02,  2.63657284e-02, -6.85230380e-03],
       [-9.99782619e-01,  1.00020375e+00, -1.18930446e-02,
        -1.49679971e-02,  1.23286933e-02, -3.89798958e-02,
        -2.21386103e-02,  9.18098009e-02,  4.17905970e-03,
        -4.17905970e-03,  5.81822799e-02,  3.86893385e-02,
        -9.37551424e-02,  1.16961069e-02, -3.01553607e-02,
         2.18676908e-02,  8.29998118e-02, -3.61453706e-02,
         5.30186226e-02, -2.60251666e-02,  6.94019367e-03],
       [-1.71315422e-02, -1.18930446e-02,  1.00020375e+00,
        -5.47816782e-03, -9.57913672e-04,  1.23341300e-02,
        -6.18161305e-03, -5.68089791e-03,  1.44849814e-02,
        -1.44849814e-02, -9.39318979e-03,  3.14903405e-02,
        -1.11124283e-02, -6.00064307e-03, -1.06765605e-02,
        -4.54103072e-03, -3.25811921e-03, -1.95713265e-02,
         1.22215689e-02, -1.18044866e-02, -3.01065101e-03],
       [ 1.51258237e-02, -1.49679971e-02, -5.47816782e-03,
         1.00020375e+00, -2.57500324e-02, -4.44237576e-01,
        -1.66170231e-01, -1.52710322e-01, -1.02890420e-02,
         1.02890420e-02, -9.86035145e-02,  3.01015984e-02,
         4.69072396e-02,  3.14082128e-02,  1.33620127e-01,
         1.92355652e-02,  5.09569010e-03,  1.37943202e-01,
         1.77263601e-02,  7.95998244e-02,  3.55388259e-03],
       [-1.22999597e-02,  1.23286933e-02, -9.57913672e-04,
        -2.57500324e-02,  1.00020375e+00, -7.76794836e-02,
        -2.90565645e-02, -2.67029617e-02, -2.34349967e-02,
         2.34349967e-02,  8.99398275e-03, -3.04254838e-02,
         3.58729019e-02, -2.82059183e-02, -7.94001902e-02,
        -2.13450358e-02, -1.53147326e-02, -9.19946796e-02,
        -1.39935042e-02, -2.86078697e-02, -1.41515126e-02],
       [ 3.86190242e-02, -3.89798958e-02,  1.23341300e-02,
        -4.44237576e-01, -7.76794836e-02,  1.00020375e+00,
        -5.01281612e-01, -4.60677438e-01,  1.71585184e-02,
        -1.71585184e-02, -2.14556483e-01,  2.48774814e-02,
         1.10893451e-01,  9.91353990e-02,  1.20045761e-01,
        -4.63759838e-03, -2.79265320e-04,  1.56850414e-01,
         9.27474413e-03,  2.08071292e-01,  1.49368716e-02],
       [ 2.23163042e-02, -2.21386103e-02, -6.18161305e-03,
        -1.66170231e-01, -2.90565645e-02, -5.01281612e-01,
         1.00020375e+00, -1.72319679e-01, -1.21779701e-02,
         1.21779701e-02, -1.07247134e-01,  9.63731619e-02,
         2.95347715e-02, -3.68036488e-03,  3.27413745e-01,
         1.11817179e-01,  8.15008850e-02,  1.91508409e-01,
         6.90647753e-02,  7.27156739e-02,  5.53669565e-02],
       [-9.16379759e-02,  9.18098009e-02, -5.68089791e-03,
        -1.52710322e-01, -2.67029617e-02, -4.60677438e-01,
        -1.72319679e-01,  1.00020375e+00,  2.79084624e-03,
        -2.79084624e-03,  5.17073828e-01, -1.61512235e-01,
        -2.43692627e-01, -1.63953968e-01, -6.35066106e-01,
        -1.26586532e-01, -8.80894619e-02, -5.45573571e-01,
        -1.01202666e-01, -4.48764974e-01, -8.09876415e-02],
       [-4.59906393e-03,  4.17905970e-03,  1.44849814e-02,
        -1.02890420e-02, -2.34349967e-02,  1.71585184e-02,
        -1.21779701e-02,  2.79084624e-03,  1.00020375e+00,
        -1.00020375e+00,  6.41219291e-03, -5.90290318e-03,
         2.13505407e-02, -3.09993390e-02, -1.09503450e-02,
         1.07436503e-03,  2.36222512e-03, -4.99018768e-03,
         7.61809388e-03,  1.22466140e-04, -6.03265536e-03],
       [ 4.59906393e-03, -4.17905970e-03, -1.44849814e-02,
         1.02890420e-02,  2.34349967e-02, -1.71585184e-02,
         1.21779701e-02, -2.79084624e-03, -1.00020375e+00,
         1.00020375e+00, -6.41219291e-03,  5.90290318e-03,
        -2.13505407e-02,  3.09993390e-02,  1.09503450e-02,
        -1.07436503e-03, -2.36222512e-03,  4.99018768e-03,
        -7.61809388e-03, -1.22466140e-04,  6.03265536e-03],
       [-5.79052883e-02,  5.81822799e-02, -9.39318979e-03,
        -9.86035145e-02,  8.99398275e-03, -2.14556483e-01,
        -1.07247134e-01,  5.17073828e-01,  6.41219291e-03,
        -6.41219291e-03,  1.00020375e+00, -2.98348747e-01,
        -5.12198316e-01, -2.76583946e-01, -3.89655997e-01,
        -1.43248630e-01, -7.44836162e-02, -3.38238323e-01,
        -1.03245934e-01, -2.70394905e-01, -7.50308534e-02],
       [-3.96001774e-02,  3.86893385e-02,  3.14903405e-02,
         3.01015984e-02, -3.04254838e-02,  2.48774814e-02,
         9.63731619e-02, -1.61512235e-01, -5.90290318e-03,
         5.90290318e-03, -2.98348747e-01,  1.00020375e+00,
        -3.52955614e-01, -1.90593865e-01,  2.42453051e-01,
         6.20904696e-02,  7.13534812e-02,  1.76043055e-01,
         7.42649566e-02,  1.07052365e-01,  5.73313900e-02],
       [ 9.40704744e-02, -9.37551424e-02, -1.11124283e-02,
         4.69072396e-02,  3.58729019e-02,  1.10893451e-01,
         2.95347715e-02, -2.43692627e-01,  2.13505407e-02,
        -2.13505407e-02, -5.12198316e-01, -3.52955614e-01,
         1.00020375e+00, -3.27207194e-01,  1.24401893e-01,
         6.67301382e-02, -2.06887410e-02,  1.05274453e-01,
         3.20913732e-02,  1.07985979e-01,  1.07253798e-02],
       [-1.15210927e-02,  1.16961069e-02, -6.00064307e-03,
         3.14082128e-02, -2.82059183e-02,  9.91353990e-02,
        -3.68036488e-03, -1.63953968e-01, -3.09993390e-02,
         3.09993390e-02, -2.76583946e-01, -1.90593865e-01,
        -3.27207194e-01,  1.00020375e+00,  7.68171091e-02,
         2.82200740e-02,  4.86956395e-02,  1.06595500e-01,
         1.09834006e-02,  8.83420294e-02,  2.15348119e-02],
       [ 3.04628787e-02, -3.01553607e-02, -1.06765605e-02,
         1.33620127e-01, -7.94001902e-02,  1.20045761e-01,
         3.27413745e-01, -6.35066106e-01, -1.09503450e-02,
         1.09503450e-02, -3.89655997e-01,  2.42453051e-01,
         1.24401893e-01,  7.68171091e-02,  1.00020375e+00,
         2.74480787e-01,  2.57175165e-01,  6.80920361e-01,
         2.35886207e-01,  3.33465925e-01,  2.32378193e-01],
       [-2.17342582e-02,  2.18676908e-02, -4.54103072e-03,
         1.92355652e-02, -2.13450358e-02, -4.63759838e-03,
         1.11817179e-01, -1.26586532e-01,  1.07436503e-03,
        -1.07436503e-03, -1.43248630e-01,  6.20904696e-02,
         6.67301382e-02,  2.82200740e-02,  2.74480787e-01,
         1.00020375e+00,  1.16014625e-01,  1.62439351e-01,
         1.80579485e-01,  1.67844776e-01,  1.42543643e-01],
       [-8.28989600e-02,  8.29998118e-02, -3.25811921e-03,
         5.09569010e-03, -1.53147326e-02, -2.79265320e-04,
         8.15008850e-02, -8.80894619e-02,  2.36222512e-03,
        -2.36222512e-03, -7.44836162e-02,  7.13534812e-02,
        -2.06887410e-02,  4.86956395e-02,  2.57175165e-01,
         1.16014625e-01,  1.00020375e+00,  1.11267787e-01,
         1.54556604e-01,  4.13658694e-02,  1.37965892e-01],
       [ 3.67105396e-02, -3.61453706e-02, -1.95713265e-02,
         1.37943202e-01, -9.19946796e-02,  1.56850414e-01,
         1.91508409e-01, -5.45573571e-01, -4.99018768e-03,
         4.99018768e-03, -3.38238323e-01,  1.76043055e-01,
         1.05274453e-01,  1.06595500e-01,  6.80920361e-01,
         1.62439351e-01,  1.11267787e-01,  1.00020375e+00,
         1.51408220e-01,  3.41764272e-01,  1.05110556e-01],
       [-5.33692356e-02,  5.30186226e-02,  1.22215689e-02,
         1.77263601e-02, -1.39935042e-02,  9.27474413e-03,
         6.90647753e-02, -1.01202666e-01,  7.61809388e-03,
        -7.61809388e-03, -1.03245934e-01,  7.42649566e-02,
         3.20913732e-02,  1.09834006e-02,  2.35886207e-01,
         1.80579485e-01,  1.54556604e-01,  1.51408220e-01,
         1.00020375e+00,  1.75537935e-01,  1.38964170e-01],
       [ 2.63657284e-02, -2.60251666e-02, -1.18044866e-02,
         7.95998244e-02, -2.86078697e-02,  2.08071292e-01,
         7.27156739e-02, -4.48764974e-01,  1.22466140e-04,
        -1.22466140e-04, -2.70394905e-01,  1.07052365e-01,
         1.07985979e-01,  8.83420294e-02,  3.33465925e-01,
         1.67844776e-01,  4.13658694e-02,  3.41764272e-01,
         1.75537935e-01,  1.00020375e+00,  4.23822947e-02],
       [-6.85230380e-03,  6.94019367e-03, -3.01065101e-03,
         3.55388259e-03, -1.41515126e-02,  1.49368716e-02,
         5.53669565e-02, -8.09876415e-02, -6.03265536e-03,
         6.03265536e-03, -7.50308534e-02,  5.73313900e-02,
         1.07253798e-02,  2.15348119e-02,  2.32378193e-01,
         1.42543643e-01,  1.37965892e-01,  1.05110556e-01,
         1.38964170e-01,  4.23822947e-02,  1.00020375e+00]])

In [15]:
#eigendecomposition
x,y = np.linalg.eig(covariance_matrix)
print(x,y)

[ 3.45463373e+00+0.00000000e+00j  2.08864974e+00+0.00000000e+00j
  2.00918463e+00+0.00000000e+00j  1.70664559e+00+0.00000000e+00j
  2.34105889e-01+0.00000000e+00j  4.19278666e-01+0.00000000e+00j
  1.41240416e+00+0.00000000e+00j  1.25697453e+00+0.00000000e+00j
  6.74171853e-01+0.00000000e+00j  1.17527664e+00+0.00000000e+00j
  1.10922744e+00+0.00000000e+00j  8.02177832e-01+0.00000000e+00j
  8.50956151e-01+0.00000000e+00j  8.69974956e-01+0.00000000e+00j
  1.01390401e+00+0.00000000e+00j  9.92498258e-01+0.00000000e+00j
  9.34214654e-01+0.00000000e+00j -8.01471784e-17+0.00000000e+00j
 -2.39617802e-16+0.00000000e+00j  4.01406909e-16+8.29749741e-17j
  4.01406909e-16-8.29749741e-17j] [[-6.42621565e-02+0.00000000e+00j -6.37986429e-01+0.00000000e+00j
  -6.60085677e-02+0.00000000e+00j -2.04312496e-01+0.00000000e+00j
   3.18291190e-03+0.00000000e+00j -1.72161849e-02+0.00000000e+00j
  -1.69416533e-01+0.00000000e+00j -5.96771164e-02+0.00000000e+00j
   3.88806677e-03+0.00000000e+00j  4.56622148e-02+0.00000000e+00j
  -6.14305676e-02+0.00000000e+00j  3.75993982e-03+0.00000000e+00j
   4.96268895e-02+0.00000000e+00j  2.50544999e-02+0.00000000e+00j
   1.88974231e-02+0.00000000e+00j -3.15840754e-02+0.00000000e+00j
   3.51213772e-03+0.00000000e+00j  4.73983745e-01+0.00000000e+00j
  -4.48735908e-01+0.00000000e+00j  3.65027065e-02-1.57852863e-02j
   3.65027065e-02+1.57852863e-02j]
 [ 6.41826794e-02+0.00000000e+00j  6.37933081e-01+0.00000000e+00j
   6.53889293e-02+0.00000000e+00j  2.03955310e-01+0.00000000e+00j
  -3.33453203e-03+0.00000000e+00j  1.80287435e-02+0.00000000e+00j
   1.70662267e-01+0.00000000e+00j  6.03880782e-02+0.00000000e+00j
  -4.20196409e-03+0.00000000e+00j -4.18270146e-02+0.00000000e+00j
   6.39647419e-02+0.00000000e+00j -5.76958977e-03+0.00000000e+00j
  -4.56313867e-02+0.00000000e+00j -2.77125646e-02+0.00000000e+00j
  -3.64257252e-02+0.00000000e+00j  9.66565553e-03+0.00000000e+00j
  -5.10158462e-03+0.00000000e+00j  4.73947720e-01+0.00000000e+00j
  -4.48701802e-01+0.00000000e+00j  3.64999321e-02-1.57840865e-02j
   3.64999321e-02+1.57840865e-02j]
 [ 2.90702167e-03+0.00000000e+00j  3.50936201e-03+0.00000000e+00j
   2.15250271e-02+0.00000000e+00j  1.28434355e-02+0.00000000e+00j
   5.21634432e-03+0.00000000e+00j -2.79548811e-02+0.00000000e+00j
  -4.24830556e-02+0.00000000e+00j -2.43427404e-02+0.00000000e+00j
   1.08064108e-02+0.00000000e+00j -1.32276851e-01+0.00000000e+00j
  -8.71642624e-02+0.00000000e+00j  6.92407238e-02+0.00000000e+00j
  -1.37811107e-01+0.00000000e+00j  9.15286877e-02+0.00000000e+00j
   6.03958652e-01+0.00000000e+00j  7.55370043e-01+0.00000000e+00j
   5.47615867e-02+0.00000000e+00j  1.37539515e-02+0.00000000e+00j
  -1.30213156e-02+0.00000000e+00j  1.05922716e-03-4.58053815e-04j
   1.05922716e-03+4.58053815e-04j]
 [-7.05415431e-02+0.00000000e+00j  2.89886025e-02+0.00000000e+00j
  -3.44260133e-02+0.00000000e+00j -2.78554855e-01+0.00000000e+00j
  -8.17900230e-02+0.00000000e+00j  2.02666456e-01+0.00000000e+00j
   2.14957270e-01+0.00000000e+00j  6.13175937e-01+0.00000000e+00j
  -4.20016723e-03+0.00000000e+00j  4.06013880e-02+0.00000000e+00j
  -5.03804507e-01+0.00000000e+00j  4.59868693e-02+0.00000000e+00j
  -3.27183811e-02+0.00000000e+00j  3.25397588e-02+0.00000000e+00j
  -2.12060998e-02+0.00000000e+00j  1.24584845e-03+0.00000000e+00j
  -4.98543689e-02+0.00000000e+00j  2.74650445e-01+0.00000000e+00j
   2.70892300e-01+0.00000000e+00j -1.82283397e-01-7.81771882e-02j
  -1.82283397e-01+7.81771882e-02j]
 [ 4.23576900e-02+0.00000000e+00j -8.72593996e-03+0.00000000e+00j
  -3.07541678e-02+0.00000000e+00j  9.78202771e-03+0.00000000e+00j
   2.89148022e-02+0.00000000e+00j -8.65943115e-02+0.00000000e+00j
   1.71837158e-01+0.00000000e+00j -1.73965499e-02+0.00000000e+00j
  -9.52129399e-02+0.00000000e+00j -1.88056736e-02+0.00000000e+00j
   5.79167030e-02+0.00000000e+00j  7.79694029e-02+0.00000000e+00j
  -1.57581535e-01+0.00000000e+00j  1.07071322e-01+0.00000000e+00j
   7.13453961e-01+0.00000000e+00j -6.15167402e-01+0.00000000e+00j
   9.50607346e-02+0.00000000e+00j  5.48493390e-02+0.00000000e+00j
   5.40988149e-02+0.00000000e+00j -3.64030863e-02-1.56124528e-02j
  -3.64030863e-02+1.56124528e-02j]
 [-1.65072980e-01+0.00000000e+00j -1.33209382e-01+0.00000000e+00j
   6.48255300e-02+0.00000000e+00j  6.53589855e-01+0.00000000e+00j
  -5.04898884e-02+0.00000000e+00j  1.50112516e-01+0.00000000e+00j
  -1.98312733e-01+0.00000000e+00j -1.94026041e-01+0.00000000e+00j
  -8.88977628e-02+0.00000000e+00j -3.83684018e-02+0.00000000e+00j
  -5.37212772e-02+0.00000000e+00j  5.53716318e-02+0.00000000e+00j
  -4.15421331e-02+0.00000000e+00j  4.12855472e-02+0.00000000e+00j
  -4.81776503e-02+0.00000000e+00j -1.24371683e-02+0.00000000e+00j
  -2.14311764e-02+0.00000000e+00j  4.06230057e-01+0.00000000e+00j
   4.00671458e-01+0.00000000e+00j -2.69611778e-01-1.15630337e-01j
  -2.69611778e-01+1.15630337e-01j]
 [-1.38393421e-01+0.00000000e+00j  9.96901292e-02+0.00000000e+00j
  -4.16658448e-02+0.00000000e+00j -4.86086053e-01+0.00000000e+00j
  -1.87950766e-01+0.00000000e+00j  2.11259610e-01+0.00000000e+00j
   5.70232356e-02+0.00000000e+00j -1.69198688e-01+0.00000000e+00j
   1.09181768e-01+0.00000000e+00j -5.80322173e-02+0.00000000e+00j
   6.09436828e-01+0.00000000e+00j -9.76135394e-02+0.00000000e+00j
  -2.49954527e-02+0.00000000e+00j -4.24158532e-03+0.00000000e+00j
   2.96720379e-03+0.00000000e+00j  7.48729292e-02+0.00000000e+00j
   3.65357056e-02+0.00000000e+00j  2.99415981e-01+0.00000000e+00j
   2.95318959e-01+0.00000000e+00j -1.98720093e-01-8.52265121e-02j
  -1.98720093e-01+8.52265121e-02j]
 [ 4.45063013e-01+0.00000000e+00j  5.94916138e-02+0.00000000e+00j
  -9.63074732e-03+0.00000000e+00j -1.55971323e-01+0.00000000e+00j
   3.46220250e-01+0.00000000e+00j -6.20902409e-01+0.00000000e+00j
  -1.76412509e-02+0.00000000e+00j -1.34621828e-01+0.00000000e+00j
   3.47345928e-02+0.00000000e+00j  8.09771082e-02+0.00000000e+00j
  -9.02509941e-02+0.00000000e+00j -3.60651471e-02+0.00000000e+00j
   1.48852300e-01+0.00000000e+00j -1.07454271e-01+0.00000000e+00j
  -5.18475310e-02+0.00000000e+00j  5.68393544e-02+0.00000000e+00j
   2.21391102e-02+0.00000000e+00j  2.82085410e-01+0.00000000e+00j
   2.78225530e-01+0.00000000e+00j -1.87217927e-01-8.02934954e-02j
  -1.87217927e-01+8.02934954e-02j]
 [ 6.23836622e-03+0.00000000e+00j -4.45751361e-02+0.00000000e+00j
   6.99315139e-01+0.00000000e+00j -7.20011613e-02+0.00000000e+00j
   3.13235566e-03+0.00000000e+00j -1.33812321e-03+0.00000000e+00j
  -3.02251994e-02+0.00000000e+00j  3.49962148e-02+0.00000000e+00j
  -1.30007508e-03+0.00000000e+00j  1.59813174e-02+0.00000000e+00j
   1.78980241e-02+0.00000000e+00j -7.59505958e-04+0.00000000e+00j
  -3.41325441e-03+0.00000000e+00j -8.19682808e-03+0.00000000e+00j
   1.56230394e-02+0.00000000e+00j -2.59941005e-02+0.00000000e+00j
  -4.66789904e-03+0.00000000e+00j  1.78027838e-03+0.00000000e+00j
  -4.13092369e-03+0.00000000e+00j  6.62916898e-02-2.94320314e-01j
   6.62916898e-02+2.94320314e-01j]
 [-6.23836622e-03+0.00000000e+00j  4.45751361e-02+0.00000000e+00j
  -6.99315139e-01+0.00000000e+00j  7.20011613e-02+0.00000000e+00j
  -3.13235566e-03+0.00000000e+00j  1.33812321e-03+0.00000000e+00j
   3.02251994e-02+0.00000000e+00j -3.49962148e-02+0.00000000e+00j
   1.30007508e-03+0.00000000e+00j -1.59813174e-02+0.00000000e+00j
  -1.78980241e-02+0.00000000e+00j  7.59505958e-04+0.00000000e+00j
   3.41325441e-03+0.00000000e+00j  8.19682808e-03+0.00000000e+00j
  -1.56230394e-02+0.00000000e+00j  2.59941005e-02+0.00000000e+00j
   4.66789904e-03+0.00000000e+00j  1.78027838e-03+0.00000000e+00j
  -4.13092369e-03+0.00000000e+00j  6.62916898e-02-2.94320314e-01j
   6.62916898e-02+2.94320314e-01j]
 [ 3.68291190e-01+0.00000000e+00j  5.60302142e-02+0.00000000e+00j
  -6.31851943e-03+0.00000000e+00j -1.20880600e-01+0.00000000e+00j
  -4.00021656e-02+0.00000000e+00j  1.74052813e-01+0.00000000e+00j
  -2.04610330e-01+0.00000000e+00j -1.31320473e-01+0.00000000e+00j
  -5.19139656e-02+0.00000000e+00j  6.72457763e-02+0.00000000e+00j
  -9.47731444e-02+0.00000000e+00j  1.74663962e-01+0.00000000e+00j
  -4.40393625e-01+0.00000000e+00j  3.60879897e-01+0.00000000e+00j
  -1.73546637e-01+0.00000000e+00j -2.58065337e-02+0.00000000e+00j
   2.42765763e-01+0.00000000e+00j  2.01629446e-01+0.00000000e+00j
   2.40213447e-01+0.00000000e+00j  4.20535907e-01+3.46944695e-17j
   4.20535907e-01-3.46944695e-17j]
 [-1.52524602e-01+0.00000000e+00j  1.47529795e-01+0.00000000e+00j
  -6.89222137e-03+0.00000000e+00j -1.25487977e-01+0.00000000e+00j
  -3.29517424e-02+0.00000000e+00j -3.65102858e-02+0.00000000e+00j
  -3.61365520e-01+0.00000000e+00j -2.43829929e-02+0.00000000e+00j
   5.40710867e-02+0.00000000e+00j -6.34653322e-01+0.00000000e+00j
  -1.76824608e-01+0.00000000e+00j -5.73635751e-02+0.00000000e+00j
   2.67348134e-01+0.00000000e+00j -2.36954199e-01+0.00000000e+00j
   9.60397343e-02+0.00000000e+00j -1.38624314e-01+0.00000000e+00j
  -1.06705791e-01+0.00000000e+00j  1.65141534e-01+0.00000000e+00j
   1.96743174e-01+0.00000000e+00j  3.44433546e-01+1.04083409e-17j
   3.44433546e-01-1.04083409e-17j]
 [-1.61099964e-01+0.00000000e+00j -1.97622894e-01+0.00000000e+00j
   4.34838068e-02+0.00000000e+00j  1.16459922e-01+0.00000000e+00j
   2.64475321e-02+0.00000000e+00j -9.01789234e-02+0.00000000e+00j
   7.17003618e-01+0.00000000e+00j -1.69405548e-01+0.00000000e+00j
   2.21344625e-02+0.00000000e+00j  2.04150171e-02+0.00000000e+00j
   5.42237662e-03+0.00000000e+00j -4.83364249e-02+0.00000000e+00j
   9.50157502e-02+0.00000000e+00j -3.17769243e-02+0.00000000e+00j
  -4.35226815e-02+0.00000000e+00j  1.02401619e-01+0.00000000e+00j
  -1.16392513e-01+0.00000000e+00j  2.12842285e-01+0.00000000e+00j
   2.53571985e-01+0.00000000e+00j  4.43922379e-01+0.00000000e+00j
   4.43922379e-01-0.00000000e+00j]
 [-9.42361523e-02+0.00000000e+00j  4.08141998e-02+0.00000000e+00j
  -4.36265652e-02+0.00000000e+00j  1.29475625e-01+0.00000000e+00j
   5.02260871e-02+0.00000000e+00j -6.29306204e-02+0.00000000e+00j
  -3.29457743e-01+0.00000000e+00j  4.24352476e-01+0.00000000e+00j
  -2.02299443e-02+0.00000000e+00j  5.54042080e-01+0.00000000e+00j
   3.00636471e-01+0.00000000e+00j -9.85391134e-02+0.00000000e+00j
   1.55703216e-01+0.00000000e+00j -1.71303000e-01+0.00000000e+00j
   1.81030961e-01+0.00000000e+00j  4.01685283e-02+0.00000000e+00j
  -4.17835689e-02+0.00000000e+00j  1.56853999e-01+0.00000000e+00j
   1.86869728e-01+0.00000000e+00j  3.27148341e-01-1.17961196e-16j
   3.27148341e-01+1.17961196e-16j]
 [-4.47430714e-01+0.00000000e+00j  9.39410426e-02+0.00000000e+00j
  -7.46947697e-03+0.00000000e+00j -1.43612607e-01+0.00000000e+00j
   7.95985459e-01+0.00000000e+00j  9.01404208e-02+0.00000000e+00j
  -5.17135003e-02+0.00000000e+00j -3.50079877e-02+0.00000000e+00j
  -2.36331919e-01+0.00000000e+00j -1.76649453e-02+0.00000000e+00j
   2.93445179e-02+0.00000000e+00j  8.40966966e-02+0.00000000e+00j
  -1.79029843e-01+0.00000000e+00j  1.33576316e-01+0.00000000e+00j
  -6.86451339e-02+0.00000000e+00j  5.33686494e-03+0.00000000e+00j
  -7.71319373e-02+0.00000000e+00j -1.13760405e-16+0.00000000e+00j
  -9.15259621e-17+0.00000000e+00j  1.15560675e-16+2.43483144e-17j
   1.15560675e-16-2.43483144e-17j]
 [-1.82408005e-01+0.00000000e+00j  1.06535672e-01+0.00000000e+00j
   6.51093864e-03+0.00000000e+00j -1.26860106e-01+0.00000000e+00j
  -9.58321952e-02+0.00000000e+00j  4.97771057e-02+0.00000000e+00j
   2.07651846e-02+0.00000000e+00j -2.43187218e-01+0.00000000e+00j
  -1.22785999e-01+0.00000000e+00j  2.36148087e-01+0.00000000e+00j
  -1.49652335e-01+0.00000000e+00j  6.38960445e-01+0.00000000e+00j
   1.76429377e-01+0.00000000e+00j -4.32258598e-01+0.00000000e+00j
   9.92155282e-03+0.00000000e+00j  1.40048378e-02+0.00000000e+00j
   3.85007558e-01+0.00000000e+00j -2.52493615e-16+0.00000000e+00j
   1.22690372e-16+0.00000000e+00j -2.07648479e-17-3.66761301e-18j
  -2.07648479e-17+3.66761301e-18j]
 [-1.28884777e-01+0.00000000e+00j  1.81759996e-01+0.00000000e+00j
   1.03017192e-02+0.00000000e+00j -1.03455769e-01+0.00000000e+00j
  -1.12976862e-01+0.00000000e+00j -3.69100035e-02+0.00000000e+00j
  -1.02024929e-01+0.00000000e+00j -2.34315942e-01+0.00000000e+00j
   2.48244538e-01+0.00000000e+00j  2.56453942e-01+0.00000000e+00j
  -1.45111840e-01+0.00000000e+00j  2.66665203e-01+0.00000000e+00j
   3.69556373e-01+0.00000000e+00j  5.41011756e-01+0.00000000e+00j
   7.85492727e-02+0.00000000e+00j -4.08265016e-02+0.00000000e+00j
  -4.51042630e-01+0.00000000e+00j  1.41386768e-16+0.00000000e+00j
   1.81728212e-16+0.00000000e+00j  3.97180533e-18-4.72956924e-17j
   3.97180533e-18+4.72956924e-17j]
 [-4.00592131e-01+0.00000000e+00j  4.57488805e-02+0.00000000e+00j
  -1.81610542e-03+0.00000000e+00j -5.21440779e-02+0.00000000e+00j
  -3.87427676e-01+0.00000000e+00j -6.31238349e-01+0.00000000e+00j
  -5.57498038e-02+0.00000000e+00j  1.15475259e-01+0.00000000e+00j
  -3.55326872e-01+0.00000000e+00j -6.41850635e-02+0.00000000e+00j
   5.22512572e-02+0.00000000e+00j  6.81667196e-02+0.00000000e+00j
  -2.70769492e-01+0.00000000e+00j  1.87928413e-01+0.00000000e+00j
  -1.50421016e-01+0.00000000e+00j  2.29582858e-02+0.00000000e+00j
   1.28636594e-02+0.00000000e+00j  5.48433021e-17+0.00000000e+00j
   3.39924942e-16+0.00000000e+00j -2.98319602e-16-5.33052529e-17j
  -2.98319602e-16+5.33052529e-17j]
 [-1.61764324e-01+0.00000000e+00j  1.44038960e-01+0.00000000e+00j
   1.96514958e-02+0.00000000e+00j -9.40219488e-02+0.00000000e+00j
  -6.66177166e-02+0.00000000e+00j  7.89044541e-02+0.00000000e+00j
  -2.64739615e-02+0.00000000e+00j -2.66639895e-01+0.00000000e+00j
  -2.61114819e-01+0.00000000e+00j  2.18981984e-01+0.00000000e+00j
  -2.98531109e-01+0.00000000e+00j -6.18376051e-01+0.00000000e+00j
   2.60405828e-01+0.00000000e+00j  1.66458640e-01+0.00000000e+00j
   6.71511520e-02+0.00000000e+00j  2.03970812e-03+0.00000000e+00j
   4.16797676e-01+0.00000000e+00j -3.32986185e-17+0.00000000e+00j
  -3.77898781e-17+0.00000000e+00j -6.91975574e-17+4.99646978e-17j
  -6.91975574e-17-4.99646978e-17j]
 [-3.06316936e-01+0.00000000e+00j  5.79079320e-03+0.00000000e+00j
   1.27590316e-02+0.00000000e+00j  9.65787548e-02+0.00000000e+00j
   9.87115108e-02+0.00000000e+00j -1.91705472e-01+0.00000000e+00j
  -1.39766151e-02+0.00000000e+00j  9.25231124e-02+0.00000000e+00j
   7.68827202e-01+0.00000000e+00j -1.92189547e-02+0.00000000e+00j
  -3.75967769e-02+0.00000000e+00j -2.77270028e-02+0.00000000e+00j
  -1.11675597e-01+0.00000000e+00j  1.15445276e-01+0.00000000e+00j
  -4.63230435e-02+0.00000000e+00j -5.36859435e-02+0.00000000e+00j
   4.65748147e-01+0.00000000e+00j -9.24636285e-17+0.00000000e+00j
   1.61945124e-16+0.00000000e+00j  1.19075405e-16-8.39030615e-17j
   1.19075405e-16+8.39030615e-17j]
 [-1.26986792e-01+0.00000000e+00j  9.04416541e-02+0.00000000e+00j
  -4.50129950e-03+0.00000000e+00j -1.07965248e-01+0.00000000e+00j
  -9.45114854e-02+0.00000000e+00j -1.45948717e-02+0.00000000e+00j
  -8.54939303e-02+0.00000000e+00j -3.06905321e-01+0.00000000e+00j
   2.12433763e-01+0.00000000e+00j  2.75287441e-01+0.00000000e+00j
  -2.75752128e-01+0.00000000e+00j -2.30143646e-01+0.00000000e+00j
  -5.23437729e-01+0.00000000e+00j -4.16925996e-01+0.00000000e+00j
   6.56267510e-02+0.00000000e+00j -4.75686141e-02+0.00000000e+00j
  -3.86098157e-01+0.00000000e+00j  3.46813495e-16+0.00000000e+00j
   4.77626052e-17+0.00000000e+00j -6.51425917e-17-3.25466008e-17j
  -6.51425917e-17+3.25466008e-17j]]